### ISSUE TITLE
not able to access admin LTE throws error 

### ISSUE THREAD

**Issue by sanchay160887** [yasharma/MEAN-AdminLTE#1]
URL I am try to access - http://localhost:9000/admin

{"errors":{"source":{"name":"UnauthorizedError","message":"No authorization token was found","code":"credentials_required","status":401,"inner":{"message":"No authorization token was found"}},"code":"credentials_required","message":"No authorization token was found","success":false}}

**Comment by yasharma** [comment]
@sanchay160887 admin url is http://localhost:9000/admin.html not http://localhost:9000/admin
